### PR TITLE
implement suggested fixes to lsps1

### LINKED ISSUE #575: Use a smaller value for `funding_confirms_within_blocks` in LSPS1-client.
I've found a few issues related to LSPS1-spec compliance.

- **Pick lower default value for `funding_confirms_within_blocks`**
  By default the LSP-client sets `funding_confirms_within_blocks` to 288.
  However, the spec only allows values up to and inclusive of 255 blocks.
  See https://github.com/BitcoinAndLightningLayerSpecs/lsp/issues/112 for  more context.
- **Use `bolt11_invoice` instead of `lightning_invoice`**.
  The spec isn't very consistent and uses `bolt11_invoice` and `lightning_invoice`.
  However, `lightning_invoice` is only used in some examples.
  I expect the spec will use `bolt11_invoice` only.
  See https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/109
- **Use `required_channel_confirmations`-field**
  This field is not set by the client

### PR DESCRIPTION
**Pull request by niteshbalusu11**
fixes #575

### CODE REVIEW

File: lsp/process_order.js [hunk 1]
```diff
@@ -453,7 +453,7 @@ module.exports = (args, cbk) => {
             order_state: orderStateCreated,
             payment: {
               fee_total_sat: makeInvoice.tokens.toString(),
-              lightning_invoice: makeInvoice.request,
+              bolt11_invoice: makeInvoice.request,
```
Comment (alexbosworth) [inline lsp/process_order.js:456]: changes alphabetical order

**Review by alexbosworth — APPROVED** [review]
